import site from '../data/site.json';

/**
 * Per-page metadata: share card, description, and a canonical URL on the public domain.
 * Cards live in public/og and are generated by scripts/og-images.py; the generator's list and the
 * callers here are the same set, so a page cannot declare a card that does not exist.
 *
 * `path` matters: without a canonical, the preview host and the real domain look like two copies
 * of the same page to a crawler.
 */
export function og(name, { title, description, path } = {}) {
  const image = { url: `/og/${name}.jpg`, width: 1200, height: 630 };
  return {
    ...(description && { description }),
    ...(path && { alternates: { canonical: new URL(path, site.domain).href } }),
    openGraph: {
      siteName: 'Illicit Shadows', type: 'website',
      ...(title && { title }), ...(description && { description }),
      ...(path && { url: new URL(path, site.domain).href }),
      images: [image],
    },
    twitter: { card: 'summary_large_image', ...(title && { title }), ...(description && { description }), images: [image] },
  };
}
