/**
 * Share card for a page. Cards live in public/og and are generated by scripts/og-images.py.
 * Passing a name that has no card would ship a broken preview, so the generator's list and this
 * one are the same set: add a page to both or to neither.
 */
export function og(name, { title, description } = {}) {
  const image = { url: `/og/${name}.jpg`, width: 1200, height: 630 };
  return {
    openGraph: { ...(title && { title }), ...(description && { description }), images: [image] },
    twitter: { card: 'summary_large_image', ...(title && { title }), ...(description && { description }), images: [image] },
  };
}
